services:
  postgresql:
    image:
      postgres:latest
    restart: always
    volumes:
      - ./data/ecommerce-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: localpw
